
package:
  name: yeahml
  version: {{ python setup.py --version }}

source:
  url: https://github.com/yeahml/yeahml

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - pip:
      - toposort
  run:
    - python
    - tensorflow
    - pyyaml
    - matplotlib

test:
  imports:
    - yeahml

about:
  home: https://github.com/yeahml/yeahml
  license: Apache
  summary: 'TODO: Fill in'
  description: |
    TODO: Fill in
  dev_url: https://github.com/yeahml/yeahml
  doc_url: https://yeahml.readthedocs.io
  doc_source_url: https://github.com/yeahml/yeahml
  